import { IonButton, IonContent, IonPage } from '@ionic/react'
import React, { useState } from 'react'
import Firebase from "firebase";
import '../assets/css/function.css'
import { useSelector } from "react-redux";
import QRCode from "qrcode.react";
import { toLower } from 'ionicons/dist/types/components/icon/utils';


const QRcode : React.FC = () =>{
    const[uname,setName] = useState('username')
    const[uaadhar,setAadhar] = useState('456789')
    const[uemail,setEmail] = useState('username@gmail.com')
    const[ucontact,setcontact] = useState('132456')
    const[ugender,setGender] = useState('M')
    const[uvalidity,setValidity] = useState(0)
    const state_username = useSelector((state:any)=> state.user.username)
    var data =[
      {
          name:uname,
          email:uemail,
          aadhar:uaadhar,
          contact:ucontact,
          gender:ugender
      }
  ]
    function getData(username:any){
        var name: string,aadhar: string,email:string,contact:string,gender:string;

        var qrid = document.getElementById('qrtag')
        var txtid = document.getElementById('qrinfo')
        qrid?.setAttribute("style","display:block")
        txtid?.setAttribute("style","display:block")

        Firebase.database().ref().child("users").on('value', function (snapshot) {
                snapshot.forEach(function(childSnapshot) {
                    name=childSnapshot.val()[0].name;
                    name=name.toLowerCase()
                    aadhar=childSnapshot.val()[0].aadhar;
                    email=childSnapshot.val()[0].email;
                    contact=childSnapshot.val()[0].contact;
                    gender=childSnapshot.val()[0].gender;
                    if(name == state_username){
                        console.log(name+'\n'+aadhar+'\n'+email+'\n'+contact+'\n'+gender+'\n');
                        setName(name)
                        setAadhar(aadhar)
                        setEmail(email)
                        setcontact(contact)
                        setGender(gender)
                        
                    }  
                });
            });
    }
    return(
        <IonPage>
            <IonContent>
                <h2 className="section-title">QR Code</h2>
                <p className="section-subtitle">QR Code will be Generated By clicking the button below</p>
            <IonButton onClick={()=>getData(0)} expand="block" fill="solid" size="default">Generate QR Code</IonButton>

            <QRCode id="qrtag" value={'Name: '+'0D0A'+uname+'\n'+'Email: '+'\n'+uemail+'\n'+'Contact Number: '+'\n'+ucontact+'\n'+'Gender: '+'\n'+ugender}></QRCode>
                
            <p className="section-subtitle" id="qrinfo">Scanning the QR Code will show up the validity details</p>

            </IonContent>
        </IonPage>
    )
}
export default QRcode;
